version: "3"

services:
  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"
    networks:
      - web
    command:
      - "--log.level=ERROR"
      - "--api"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.traefik.acme.httpchallenge=true"
      - "--certificatesresolvers.traefik.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.traefik.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.traefik.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=traefik"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=auth"

      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH}"
      - "traefik.http.middlewares.auth.basicauth.headerField=X-WebAuth-User"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.portainer.tls.certresolver=traefik"
      - "traefik.http.routers.portainer.tls=true"

volumes:
  portainer_data:

networks:
  web:
    external:
      name: web
